version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: synchtank-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql://synchtank:password@db:3306/synchtank"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: synchtank-frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend
    environment:
      BACKEND_HOST: "http://backend:8000"

  db:
    image: mysql:8
    container_name: synchtank-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: synchtank
      MYSQL_USER: synchtank
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: